### PR TITLE
New Pic for François

### PR DESCRIPTION
**Pull request by whitetigle**
New Pic for François

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Nice one, thanks!

**Comment by whitetigle** [comment]
thanks! 😁

**Comment by whitetigle** [comment]
This is because I was jealous of @Krzysztof-Cieslak's photo! 😉 

So here we go. 
From now on, you can simply call us: MWVCBH (*men wearing vibrant colors and beautiful hats*) 😁

**Comment by alfonsogarciacaro** [comment]
Hahaha, at the end we'll have to make the hat, sunglasses and bright colors the dress code for FableConf ;)

**Pull request merged**
