### PR TITLE
changed talk name to "Fable.Remoting"

### PR DESCRIPTION
**Pull request by brettrowberry**

### CODE REVIEW

**Comment by whitetigle** [comment]
Hey Brett,thanks for the PR.
We're currently discussing that with the team since it would create a discrepancy with the printed version. We'll let you know ASAP 😃

**Comment by whitetigle** [comment]
Ok Brett, basically, it's up to you. 
If you feel it's better to merge this change then I will merge this PR. 😄

**Comment by brettrowberry** [comment]
Please merge and I’ll explain why the titles don’t match during the talk.

Brett Rowberry

**Comment by whitetigle** [comment]
Done :)

**Comment by whitetigle** [comment]
I'll publish the changes today.

**Pull request merged**
